{% set name = "simage" %}
{% set version = "1.8.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}.tar.gz
  url: https://github.com/coin3d/simage/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 04effa0bdf6e943277775a498b61b2355876e85ab0679870f97a7f074e3b4955
  patches:
    - cmake.patch

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - ninja
    - cmake
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libpng
    - libjpeg-turbo
    - qt6-main
    - zlib
    - libgl-devel                        # [linux]

test:
  requires:
    - cmake      # [unix]
    - ninja
  files:
    - CMakeLists.txt      # [unix]
  commands:
    - where /r "%PREFIX%"  simage1.dll      # [win]

about:
  home: https://bitbucket.org/Coin3D/simage
  license: BSD 3-Clause
  license_family: BSD
  license_file: COPYING
  summary: Simage, image-library needed by Coin3d.
  description: This is ``simage'', a library with image format loaders and front-ends to common import libraries. simage is meant for use with applications which reads image files as textures.
  doc_url: https://bitbucket.org/Coin3D/simage
  dev_url: https://bitbucket.org/Coin3D/simage

extra:
  recipe-maintainers:
    - looooo
